config/routes.rb
IQuote::Application.routes.draw do
  
  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [ :get, :delete ], :as => 'sign_out'
    
  resource :session
  resources :users, :only => [ :new, :show, :create ] do
    resources :projects
  end
  match '/users/:user_id/projects/:id/report' => 'projects#report', :via => :get, :as => 'project_report'
  resource :user, :only => [ :edit, :update, :destroy ]
  
  resources :categories
  resources :features
  resources :feature_requests
  
  root :to => 'home#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :user
  has_many :features
  
  validates_presence_of :user_id, :title
  
  default_scope :include => :features
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base

  belongs_to :category
  
  validates_presence_of :name, :title, :points
  
end

app/models/feature_request.rb
class FeatureRequest < ActiveRecord::Base

  belongs_to :project
  belongs_to :feature
  
  validates_presence_of :project_id, :feature_id, :quantity
  validates_numericality_of :quantity
  
end

app/models/price_group.rb
class PriceGroup < ActiveRecord::Base

  belongs_to :user
  has_many :price_tiers, :order => 'min_quantity asc'
  
  validates_presence_of :user_id
  
  accepts_nested_attributes_for :price_tiers

end

app/models/price_tier.rb
class PriceTier < ActiveRecord::Base

  belongs_to :price_group
  
  validates_presence_of :price_group_id, :min_quantity, :unit_price
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  has_many :feature_requests
  has_many :features, :through => :feature_requests
  
  validates_presence_of :user_id, :title, :email, :starts_on, :ends_on, :design_completeness

  default_scope :include => [ :feature_requests, :features ]
  
  def iterations_required
    total_points = user.base_points + feature_requests.collect {|req| req.quantity * req.feature.points}.inject {|sum,e| sum+e}
    puts "total points = #{total_points}"
    magnifier = 0.85 * (1 + Math.log((6 - design_completeness)/1.25))
    puts "magnifier = #{magnifier}"
    return ((total_points*magnifier).to_f / user.points_per_iteration.to_f).ceil
  end
  
  def estimated_price(iterations)
    user.price_group.price_tiers.reverse.select {|tier| tier.min_quantity <= iterations}.first.unit_price * iterations
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  
  has_one :price_group
  has_many :categories
  has_many :projects

  validates_presence_of :points_per_iteration, :base_points
  
  accepts_nested_attributes_for :price_group
  
  after_create :generate_default_price_group
  
  def generate_default_price_group
    price_group = PriceGroup.create(:user_id => id)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 1, :unit_price => 3000)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 2, :unit_price => 2500)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 4, :unit_price => 2000)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @category.errors.full_messages.join("<br/>")
    end
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @category.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to edit_user_path
  end
  
end

app/controllers/feature_requests_controller.rb
class FeatureRequestsController < ApplicationController
  
  def create
    @feature_request = FeatureRequest.new(params[:feature_request])
    if @feature_request.save
      redirect_to user_project_path(@feature_request.project.user,@feature_request.project)
    else
      redirect_to user_project_path(@feature_request.project.user,@feature_request.project)
    end
  end
  
  def update
    @feature_request = FeatureRequest.find(params[:id])
    if @feature_request.update_attributes(params[:feature_request])
      redirect_to user_project_path(@feature_request.project.user,@feature_request.project)
    else
      redirect_to user_project_path(@feature_request.project.user,@feature_request.project)
    end
  end
  
  def destroy
    @feature_request = FeatureRequest.find(params[:id])
    project = @feature_request.project
    @feature_request.destroy
    redirect_to user_project_path(project.user,project)
  end
  
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

  before_filter :authenticate
  
  def create
    @feature = Feature.new(params[:feature])
    if @feature.save
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @feature.errors.full_messages.join("<br/>")
    end
  end
  
  def update
    @feature = Feature.find(params[:id])
    if @feature.update_attributes(params[:feature])
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @feature.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy
    redirect_to edit_user_path
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index    
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :assign_user
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    # explicitly assign user id to prevent injection
    @project.user_id = @user.id
    if @project.save
      redirect_to user_project_path(@user,@project)
    else
      redirect_to new_user_project_path(@user), :alert => @project.errors.full_messages.join("<br/>")
    end
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to user_project_path(@user,@project), :notice => 'Project updated.'
    else
      redirect_to user_project_path(@user,@project), :alert => @project.errors.full_messages.join("<br/>")
    end
  end
  
  def report
    @project = Project.find(params[:id])
  end
  
  def assign_user
    @user = User.find(params[:user_id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  
  def url_after_create
    edit_user_path
  end
  
  def url_after_destroy
    sign_in_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  
  before_filter :authenticate, :except => [ :new, :show, :create ]
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to edit_user_path, :notice => 'User updated.'
    else
      redirect_to edit_user_path, :alert => @user.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @user = current_user
    @user.destroy
    redirect_to url_after_destroy
  end
  
  private
  
  def url_after_create
    current_user = @user
    edit_user_path
  end
  
  def url_after_destroy
    sign_in_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_requests_helper.rb
module FeatureRequestsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/new.haml
= form_for @project, :url => user_projects_path(@user) do |f|
	%h1 New Project
	%p I'll guide you through the process as we go. Let's get started!

	%h2 Who Are You?
	%p
		= f.label :email
		= f.text_field :email
	
	%h2 What Do You Want To Call This Project?
	%p
		= f.label :title
		= f.text_field :title
		
	%h2 When Would You Like Work To Begin?
	%p
		= f.label :starts_on, 'Starting Date'
		= f.text_field :starts_on, :class => 'datepicker'

	%h2 When Does It Need To Be Done?
	%p
		= f.label :ends_on, 'Delivery Date'
		= f.text_field :ends_on, :class => 'datepicker'

	%h2 How Would You Describe The Level of Completeness?
	%ul
		%li
			= f.radio_button :design_completeness, 1
			Just an idea right now
		%li
			= f.radio_button :design_completeness, 2
			Basic outline for object model
		%li
			= f.radio_button :design_completeness, 3
			Some consideration for user workflows
		%li
			= f.radio_button :design_completeness, 4
			Fully storyboarded workflows
		%li
			= f.radio_button :design_completeness, 5
			Fully designed with high resolution graphics ready
			
	%p.control= f.submit 'Save + Continue'

app/views/projects/report.haml
%h1 Project Report
%p You're done! Here's a summary report of the estimated project time and cost. 

%h2 Project Info
%table.info
	%tr
		%td Title
		%td= @project.title
	%tr
		%td Estimate generated for
		%td= @project.email
	%tr
		%td Design Completeness
		%td Level #{@project.design_completeness}
		
%h2 Features
#features.categories
	- for category in @project.features.map(&:category).uniq
		%h3= category.title
		%table
			%tr
				%th FEATURE
				%th QUANTITY
			- for feature_request in @project.feature_requests.select {|req| req.feature.category==category}
				%tr
					%td= feature_request.feature.title
					%td= feature_request.quantity

%h2 Summary
%table.summary
	%tr
		%td Iterations Required:
		%td
			= count=@project.iterations_required
			weeks
	%tr
		%td Projected Start Date:
		%td= @project.starts_on.to_s(:long)
	%tr
		%td Projected Completion Date:
		%td
			= (delivery_date = @project.starts_on + count.weeks).to_s(:long)
			- if delivery_date > @project.ends_on
				%p.ui-state-error Note: delivery is past deadline! 
	%tr
		%td Total Estimated Cost: 
		%td= number_to_currency(@project.estimated_price(count))

app/views/projects/show.haml
%h1 Add Features
%p Now, select from the available options to define the features you want in your app.

- if ! @project.feature_requests.empty?
	%p.control= link_to 'Complete Estimate', project_report_path
	
.categories
	- for category in @project.user.categories
		%h3= category.title
		%table
			- for feature in category.features
				%tr
					%td= feature.title
					%td.control
						- if @project.features.include?(feature)
							- feature_request = @project.feature_requests.select {|req| req.feature==feature}.first
							%span{:id => "control_edit_#{dom_id(feature)}"}
								x #{feature_request.quantity}
								= link_to_function "edit", "$('#edit_#{dom_id(feature_request)}').show();$('#control_edit_#{dom_id(feature)}').hide()", :class => 'pencil'
							= form_for feature_request, :html => { :style => "display:none" } do |f|
								= f.label :quantity
								= f.text_field :quantity, :size => 2
								= f.submit 'Save'
								= link_to_function 'Cancel', "$('#edit_#{dom_id(feature_request)}').hide();$('#control_edit_#{dom_id(feature)}').show()"
							= link_to 'delete', feature_request, :method => :delete, :class => 'trash'
						- else
							= link_to_function 'Add', "$('#add_#{dom_id(feature)}').show();$('#control_add_#{dom_id(feature)}').hide()", :id => "control_add_#{dom_id(feature)}", :class => 'plus'
							= form_for FeatureRequest.new, :html => { :id => "add_#{dom_id(feature)}", :style => "display:none" } do |f|
								= f.hidden_field :project_id, :value => @project.id
								= f.hidden_field :feature_id, :value => feature.id
								= f.label :quantity
								= f.text_field :quantity, :size => 2
								= f.submit 'Add Feature'
								= link_to_function 'Cancel', "$('#add_#{dom_id(feature)}').hide();$('#control_add_#{dom_id(feature)}').show()"

- if ! @project.feature_requests.empty?
	%p.control= link_to 'Complete Estimate', project_report_path

app/views/users/edit.haml
%h1 Account Info
%table
	%tr
		%td Email:
		%td= @user.email
	%tr
		%td Company Name:
		%td= @user.company_name
	%tr
		%td Company URL:
		%td= @user.company_url
	%tr
		%td Points Per Iteration:
		%td= @user.points_per_iteration
	%tr
		%td Iteration Price Breaks:
		%td
			%ul
				- for tier in @user.price_group.price_tiers
					%li #{tier.min_quantity} or more = #{number_to_currency(tier.unit_price)}ea

%p.control= link_to_function 'Edit Account Info', "$('#edit_account').dialog({modal:true,title:'Edit account info',width:'40em'})"
#edit_account.categories{:style => "display:none"}
	= form_for @user, :url => { :controller => 'users', :action => 'update' } do |f|
		%h3 Account Info
		%p
			= f.label :email
			= f.text_field :email
		%p
			= f.label :company_name
			= f.text_field :company_name
		%p
			= f.label :company_url
			= f.text_field :company_url
			
		%h3 Pricing Rules
		%p
			= f.label :points_per_iteration
			= f.text_field :points_per_iteration, :size => 4
		= f.fields_for :price_group do |grp|
			%table.pricing
				%tr
					%th MIN QTY
					%th UNIT PRICE
				- for price_tier in @user.price_group.price_tiers
					= grp.fields_for :price_tiers, price_tier do |tier|
						%tr
							%td= tier.text_field :min_quantity, :size => 4
							%td= tier.text_field :unit_price, :size => 4
		%p.control= f.submit 'Update'


%h1 Categories
- if @user.categories.empty?
	%p None
- else
.categories
	- for category in @user.categories
		%h3
			= category.title
			.control{:style => 'float:right'}
				= link_to_function 'Add Feature', "$('#add_feature_to_#{dom_id(category)}').dialog({modal:true,title:'Create a new feature for category #{category.title}',width:'40em'})"
				= form_for Feature.new, :html => { :id => "add_feature_to_#{dom_id(category)}", :style => "display:none" } do |f|
					= f.hidden_field :category_id, :value => category.id
					%p
						= f.label :name
						= f.text_field :name
					%p
						= f.label :title
						= f.text_field :title
					%p
						= f.label :points
						= f.text_field :points, :size => 2
					%p.control= f.submit 'Save'
			%hr
		%table
			- if category.features.empty?
				%tr
					%td{:colspan => 4} No features
			- else
				%tr
					%th TITLE
					%th NAME
					%th POINTS
					%th
				- for feature in category.features
					%tr
						%td= feature.title
						%td= feature.name
						%td= feature.points
						%td.control
							= link_to_function 'edit', "$('#edit_#{dom_id(feature)}').dialog({modal:true,title:'Edit feature #{feature.name}',width:'40em'})", :class => 'pencil'
							= link_to 'delete', feature, :method => :delete, :class => 'trash'
							= form_for feature, :html => { :style => "display:none" } do |f|
								%p
									= f.label :name
									= f.text_field :name
								%p
									= f.label :title
									= f.text_field :title
								%p
									= f.label :points
									= f.text_field :points, :size => 2
								%p.control= f.submit 'Update'
				
%p.control= link_to_function 'Add Category', "$('#add_category').dialog({modal:true,title:'Create a new category',width:'40em'})"
#add_category{:style => "display:none"}
	= form_for Category.new do |f|
		= f.hidden_field :user_id, :value => @user.id
		%p
			= f.label :title
			= f.text_field :title
		%p.control= f.submit 'Save'

app/views/users/new.haml
%h1 Sign Up

= form_for @user do |f|
	%h2 Account Info
	%p
		= f.label :email
		= f.text_field :email
	%p
		= f.label :password 
		= f.password_field :password
	%p
		= f.label :password_confirmation
		= f.password_field :password_confirmation

	%h2 Settings
	%p
		= f.label :points_per_iteration
		= f.text_field :points_per_iteration
	%p
		= f.label :base_points
		= f.text_field :base_points
	
	%p.control= f.submit 'Create Account'

app/views/users/show.haml
%h1= @user.company_name
%p This fine company has asked me to help you get a quick estimate for your project.
%p.control= link_to 'Get Started', new_user_project_path(@user)