config/routes.rb
IQuote::Application.routes.draw do
  
  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [ :get, :delete ], :as => 'sign_out'
    
  resource :session
  resources :users, :only => [ :new, :show, :create ] do
    resources :projects
  end
  match '/users/:user_id/projects/:id/report' => 'projects#report', :via => :get, :as => 'project_report'
  resource :user, :only => [ :edit, :update, :destroy ]
  
  resources :categories
  resources :features
  resources :feature_requests
  
  root :to => 'home#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :user
  has_many :features
  
  validates_presence_of :user_id, :title
  
  default_scope :include => :features
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base

  belongs_to :category
  
  validates_presence_of :name, :title, :points
  
end

app/models/feature_request.rb
class FeatureRequest < ActiveRecord::Base

  belongs_to :project
  belongs_to :feature
  
  validates_presence_of :project_id, :feature_id, :quantity
  validates_numericality_of :quantity
  
end

app/models/price_group.rb
class PriceGroup < ActiveRecord::Base

  belongs_to :user
  has_many :price_tiers, :order => 'min_quantity asc'
  
  validates_presence_of :user_id
  
  accepts_nested_attributes_for :price_tiers

end

app/models/price_tier.rb
class PriceTier < ActiveRecord::Base

  belongs_to :price_group
  
  validates_presence_of :price_group_id, :min_quantity, :unit_price
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  has_many :feature_requests
  has_many :features, :through => :feature_requests
  
  validates_presence_of :user_id, :title, :email, :starts_on, :ends_on, :design_completeness

  default_scope :include => [ :feature_requests, :features ]
  
  def iterations_required
    total_points = user.base_points + feature_requests.collect {|req| req.quantity * req.feature.points}.inject {|sum,e| sum+e}
    puts "total points = #{total_points}"
    magnifier = 0.85 * (1 + Math.log((6 - design_completeness)/1.25))
    puts "magnifier = #{magnifier}"
    return ((total_points*magnifier).to_f / user.points_per_iteration.to_f).ceil
  end
  
  def estimated_price(iterations)
    user.price_group.price_tiers.reverse.select {|tier| tier.min_quantity <= iterations}.first.unit_price * iterations
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  
  has_one :price_group
  has_many :categories
  has_many :projects

  validates_presence_of :points_per_iteration, :base_points
  
  accepts_nested_attributes_for :price_group
  
  after_create :generate_default_price_group
  
  def generate_default_price_group
    price_group = PriceGroup.create(:user_id => id)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 1, :unit_price => 3000)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 2, :unit_price => 2500)
    PriceTier.create(:price_group_id => price_group.id, :min_quantity => 4, :unit_price => 2000)
  end
  
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

  before_filter :authenticate
  
  def create
    @feature = Feature.new(params[:feature])
    if @feature.save
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @feature.errors.full_messages.join("<br/>")
    end
  end
  
  def update
    @feature = Feature.find(params[:id])
    if @feature.update_attributes(params[:feature])
      redirect_to edit_user_path
    else
      redirect_to edit_user_path, :alert => @feature.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy
    redirect_to edit_user_path
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index    
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :assign_user
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    # explicitly assign user id to prevent injection
    @project.user_id = @user.id
    if @project.save
      redirect_to user_project_path(@user,@project)
    else
      redirect_to new_user_project_path(@user), :alert => @project.errors.full_messages.join("<br/>")
    end
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to user_project_path(@user,@project), :notice => 'Project updated.'
    else
      redirect_to user_project_path(@user,@project), :alert => @project.errors.full_messages.join("<br/>")
    end
  end
  
  def report
    @project = Project.find(params[:id])
  end
  
  def assign_user
    @user = User.find(params[:user_id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  
  def url_after_create
    edit_user_path
  end
  
  def url_after_destroy
    sign_in_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  
  before_filter :authenticate, :except => [ :new, :show, :create ]
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to edit_user_path, :notice => 'User updated.'
    else
      redirect_to edit_user_path, :alert => @user.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @user = current_user
    @user.destroy
    redirect_to url_after_destroy
  end
  
  private
  
  def url_after_create
    current_user = @user
    edit_user_path
  end
  
  def url_after_destroy
    sign_in_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_requests_helper.rb
module FeatureRequestsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
!!!
%html
	%head
	%title= yield(:title)
	= stylesheet_link_tag :all
	= javascript_include_tag :defaults
	%link{:rel=>"stylesheet", :href=>"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/themes/black-tie/jquery-ui.css", :type=>"text/css", :media=>"all"}
	= csrf_meta_tag
	%body
		#header I Quote Projects
		- if flash[:alert]
			#flash.ui-state-error=raw flash[:alert]
		- if flash[:notice]
			#flash.ui-state-highlight=raw flash[:notice]
	
		#main= yield
		#footer
			%p
				© 2011 Migrant Studios LLC. All rights reserved.
				- if signed_in?
					= link_to 'My Account', edit_user_path
					= link_to 'Sign Out', sign_out_path, :method => :delete
				- else
					= link_to 'Sign In', sign_in_path

app/views/layouts/home.haml
!!!
%html
	%head
	%title= yield(:title)
	= stylesheet_link_tag :all
	= javascript_include_tag :defaults
	%link{:rel=>"stylesheet", :href=>"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/black-tie/jquery-ui.css", :type=>"text/css", :media=>"all"}
	= csrf_meta_tag
	%body
		#header
			%h1 I Quote Projects
				
		#main= yield
		#footer
			%p © 2011 Migrant Studios LLC. All rights reserved.

app/views/layouts/projects.haml
!!!
%html
	%head
	%title= yield(:title)
	= stylesheet_link_tag :all
	= javascript_include_tag :defaults
	%link{:rel=>"stylesheet", :href=>"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/themes/black-tie/jquery-ui.css", :type=>"text/css", :media=>"all"}
	= csrf_meta_tag
	%body
		#header
			%ul
				%li.step.new
					%span 1.
					General Info
				%li.step.show
					%span 2.
					Select Features
				%li.step.report
					%span 3.
					View Report
			%hr
				
		- if flash[:alert]
			#flash.ui-state-error=raw flash[:alert]
		- if flash[:notice]
			#flash.ui-state-highlight=raw flash[:notice]
	
		#main= yield
		#footer
			%p
				© 2011 Migrant Studios LLC. All rights reserved.
				- if signed_in?
					= link_to 'My Account', edit_user_path
					= link_to 'Sign Out', sign_out_path, :method => :delete
				- else
					= link_to 'Sign In', sign_in_path

		%script
			- if ['new', 'show', 'report'].include?(controller.action_name)
				$('#header .step.#{controller.action_name}').addClass('active')